name: dev

on:
  push:
    branches:
    - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Get snapshot version
      env:
        TOKEN: ${{ secrets.SNAPSHOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node ./scripts/get-snapshot-version.mjs
    - name: Build Firefox v2
      run: npm run build:firefox_v2
    - name: Build Firefox v3
      run: npm run build:firefox_v3
    - name: Build Chrome v2
      run: npm run build:chrome_v2
    - name: Build Chrome v3
      run: npm run build:chrome_v3
    - name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist_chrome_v2
          dist_chrome_v3
          dist_firefox_v2
          dist_firefox_v3
    - name: Upload bundle analyze
      uses: actions/upload-artifact@v4
      with:
        name: bundle-analyze
        path: temp/bundle-analyze.html
    - name: Test
      run: |
        php -S 0.0.0.0:8899 -t $GITHUB_WORKSPACE/tests/simple-server &
        sleep 5
        npm run test:e2e
    # - name: Publish snapshot
    #   env:
    #     AMO_KEY: ${{ secrets.AMO_KEY }}
    #     AMO_SECRET: ${{ secrets.AMO_SECRET }}
    #     CRX_PRIV_KEY: ${{ secrets.CRX_PRIV_KEY }}
    #     CRX_PRIV_KEY_V3: ${{ secrets.CRX_PRIV_KEY_V3 }}
    #     PACK_PLATFORM: xpi,crx
    #   run: npm run pack
    # - name: Upload snapshot release
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: release
    #     path: |
    #       temp/release
    #       !temp/release/*-id.txt

  sync-locale:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Sort
      run: node ./locale/sort-origin.js
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: sync-locale
        folder: locale
        clean: false
        commit-message: '[skip ci] sync locale'
