name: release

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform(amo,cws,xpi,edge,crx)'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Build Firefox v2
      run: npm run build:firefox_v2
    - name: Build Firefox v3
      run: npm run build:firefox_v3
    - name: Build Chrome v2
      run: npm run build:chrome_v2
    - name: Build Chrome v3
      run: npm run build:chrome_v3
    - name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: dist
        retention-days: 7
        path: |
          dist_chrome_v2
          dist_chrome_v3
          dist_firefox_v2
          dist_firefox_v3
    - name: Pack
      env:
        AMO_KEY: ${{ secrets.AMO_KEY }}
        AMO_SECRET: ${{ secrets.AMO_SECRET }}
        CRX_PRIV_KEY: ${{ secrets.CRX_PRIV_KEY }}
        CRX_PRIV_KEY_V3: ${{ secrets.CRX_PRIV_KEY_V3 }}
        CWS_CLIENT_ID: ${{ secrets.CWS_CLIENT_ID }}
        CWS_CLIENT_SECRET: ${{ secrets.CWS_CLIENT_SECRET }}
        CWS_TOKEN: ${{ secrets.CWS_TOKEN }}
        MS_ACCESS_TOKEN_URL: ${{ secrets.MS_ACCESS_TOKEN_URL }}
        MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
        MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
        MS_PRODUCT_ID: ${{ secrets.MS_PRODUCT_ID }}
      run: npm run pack
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        retention-days: 7
        name: release
        path: temp/release
    - name: Release
      if: ${{ github.ref_type == 'tag' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TOKEN: ${{ secrets.SNAPSHOT_TOKEN }}
      run: npm run release
